# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  wine_chain

Parameters:
  YourEmail:
    Type: String
  Version:
    Type: String
    Default: v1
  PGHOST:
    Type: String
    Description: "Database endpoint"
  PGPORT:
    Type: String
    Description: "Database port"
  PGDATABASE:
    Type: String
    Description: "Database name"
  PGUSER:
    Type: String
    Description: "Username for database access"
  PGPASSWORD:
    Type: String
    Description: "Password for database access"

Globals:
  Function:
    Timeout: 100

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
          AdminCreateUserConfig:
            AllowAdminCreateUserOnly: false
          UserPoolName: WineChainUsers
          UsernameAttributes:
          - email
          AutoVerifiedAttributes:
          - email
          Policies:
            PasswordPolicy:
                MinimumLength: 6
                RequireLowercase: true
                RequireNumbers: false
                RequireSymbols: false
                RequireUppercase: true
  ServiceApi:
      DependsOn: UserPool
      Type: AWS::Serverless::Api
      Properties:
        Name: ServiceApi
        StageName: !Ref Version
        Cors:
          AllowMethods: "'*'"
          AllowHeaders: "'*'"
          AllowOrigin: "'*'"
        Auth:
          Authorizers:
            CognitoAuthorizer:
              UserPoolArn: !GetAtt "UserPool.Arn"
####################################################################
#Database
####################################################################
  WineSerialTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: symbol_series
          AttributeType: S
        - AttributeName: running_number
          AttributeType: S
      KeySchema: 
        - AttributeName: symbol_series
          KeyType: HASH
        - AttributeName: running_number
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: wine_serial
####################################################################
#sqs
####################################################################
  SerialGeneratorSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: src/handlers/
      Handler: dist/serialGenerator/main.serialGeneratorFunction
      Runtime: nodejs14.x
      MemorySize: 128
      Description: serialGeneratorFunction
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          PGHOST: !Ref PGHOST
          PGPORT: !Ref PGPORT
          PGUSER: !Ref PGUSER
          PGPASSWORD: !Ref PGPASSWORD
          PGDATABASE: !Ref PGDATABASE
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SerialGeneratorSqsQueue.Arn
            BatchSize: 1
  SerialGeneratorSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 200
####################################################################
#Lambda
####################################################################
  serialGeneratorPost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/serialGenerator/main.serialGeneratorPost
      Runtime: nodejs14.x
      MemorySize: 128
      Description: serialGeneratorPost.
      Policies:
        - VPCAccessPolicy: {}
      Environment:
        Variables:
          PGHOST: !Ref PGHOST
          PGPORT: !Ref PGPORT
          PGUSER: !Ref PGUSER
          PGPASSWORD: !Ref PGPASSWORD
          PGDATABASE: !Ref PGDATABASE
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/serialGenerator'
            RestApiId: !Ref ServiceApi
            Method: post
  serialGeneratorGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/serialGenerator/main.serialGeneratorGet
      Runtime: nodejs14.x
      MemorySize: 128
      Description: serialGeneratorPost.
      Policies:
        - VPCAccessPolicy: {}
      Environment:
        Variables:
          PGHOST: !Ref PGHOST
          PGPORT: !Ref PGPORT
          PGUSER: !Ref PGUSER
          PGPASSWORD: !Ref PGPASSWORD
          PGDATABASE: !Ref PGDATABASE
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/serialGenerator'
            RestApiId: !Ref ServiceApi
            Method: get
